### ISSUE TITLE
Webcam remains active after removing webcam block

### ISSUE THREAD

**Issue by sacredgeo** [matt-way/0x00#5]
The green light on my monitor (indicating webcam use) remains even after deleting the webcam block. Resetting the engine does not affect it. Otherwise, the webcam block works perfectly. 

Definitely not the top priority. Just posting here so you can take a look at it sometime.

**Comment by matt-way** [comment]
Thanks for the heads up. Some decisions need to be made surrounding what happens to running code when a block is removed. I guess it makes sense to try and destroy any events/state/etc. I am surprised that resetting did not fix it though. I'll do some testing.

**Comment by matt-way** [comment]
I've updated the webcam block to not hold onto a particular listener. Might help but needs more testing.

**Comment by matt-way** [comment]
Ok, I've fixed it, but made a new block called webcam-to-imageData, so that it is more specific to its use. To get it working I decided a good place for cleanup was by returning a function from `runOnce()`.

In other words, if you return a function from the `runOnce` function, this function will be ran whenever the block is removed. This allows you to add cleanup code, like the code necessary for the webcam block. Eg:

```
runOnce(() => {
  return () => {
    stream.getTracks().forEach(function (track) {
      track.stop()
    })
  }
})
```
